---
spring:
    profiles: default
server:
    port: 8761
eureka:
    instance:
        hostname: eurekahost
    client:
        registerWithEureka: false
        fetchRegistry: false
    serviceUrl:
        defaultZone: http://${eureka.instace.hostname}:${server.port}/eureka